account/urls.py
from django.urls import path
from . views import RegisterView, LoginView, ProfileView, LogoutView, ProfileEditView, ProfilesView

app_name = 'account'
urlpatterns = [
    path('', ProfilesView.as_view(), name='profile-list-view'),
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/<int:id>/', ProfileView.as_view(), name='profile'),
    path('profile/edit/', ProfileEditView.as_view(), name='profile-edit'),
]

api/urls.py
from django.urls import path
from .views import DetailReviewAPIView, ReviewListAPIView

app_name='api'
urlpatterns = [
    path('reviews/', ReviewListAPIView.as_view(), name="review_list"),
    path('reviews/<int:id>/', DetailReviewAPIView.as_view(), name="review_detail")
]

books/urls.py
from django.urls import path
from .views import BooksView, BooksDetailView, BooksReviewsView, EditReviewView, DeleteReviewView, \
    DeleteCompleteReview, BooksAuthorView

app_name='books'
urlpatterns = [
    path('', BooksView.as_view(), name='list'),
    path('<int:id>/', BooksDetailView.as_view(), name='detail'),
    path('<int:book_id>/author/<int:author_id>', BooksAuthorView.as_view(), name='author'),
    path('<int:id>/reviews/', BooksReviewsView.as_view(), name='reviews'),
    path('<int:book_id>/reviews/<int:review_id>/edit/', EditReviewView.as_view(), name='edit_review'),
    path('<int:book_id>/reviews/<int:review_id>/delete/', DeleteReviewView.as_view(), name='delete_review'),
    path('<int:book_id>/reviews/<int:review_id>/delete/complete/', DeleteCompleteReview.as_view(), name='delete_complete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import landing_page, home_page
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', landing_page, name='landing'),
    path('home/', home_page, name='home_page'),
    path('account/', include('account.urls')),
    path('books/', include('books.urls')),
    path('api/', include("api.urls")),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'config.views.handle_not_found'



templates/base.html
{% load static %}
{% url 'home_page' as home_page_url %}
{% url 'books:list' as books_page_url %}
{% url 'account:profile' request.user.id  as profile_page_url %}
{% url 'account:profile-edit' as profile_edit_page %}
{%url 'account:home' as account_home_page_url%}
{%url 'account:profile-list-view' as account_list_view_page_url%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{%block title%}Goodreads Clone{%endblock title%}</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
    <link href="{%static 'css/main.css'%}" rel="stylesheet" type="text/css">
    <link href="{%static 'css/custom.css'%}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css" rel="stylesheet" />
</head>
<body class="mx-2">
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-4" >
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'landing'%}">GoodReads-Clone</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">

              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link {%if request.path == home_page_url%}active{%endif%}" aria-current="page" href="{{home_page_url}}">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link {%if request.path == books_page_url%}active{%endif%}" aria-current="page" href="{{books_page_url}}">Books</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link {%if request.path == account_list_view_page_url%}active{%endif%}" aria-current="page" href="{{account_list_view_page_url}}">View Users</a>
                </li>
              </ul>

                <div class="me-5">
                    {% if request.user.is_authenticated %}
                        <ul class="navbar-nav">
                            <li class="nav-item dropdown">
                              <a class="nav-link dropdown-toggle {%if request.path == profile_page_url or request.path == profile_edit_page%}active{%endif%}" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                {{request.user.username}}
                              </a>
                              <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{%url 'account:profile' request.user.id%}">Profile</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="{% url 'account:logout' %}">Log out</a></li>
                              </ul>
                            </li>
                        </ul>
                    {%else%}
                        <a class="btn btn-light" href="{% url 'account:login' %}">Login</a>
                    {%endif%}
                </div>
            </div>
          </div>
    </nav>
    <div class="container">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{message.tags}}" role="alert">
                    {{message}}
                </div>
            {% endfor %}
        {% endif %}
        {%block content%}{%endblock content%}
    </div>

<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{%extends 'base.html'%}
{%block title%}Home Page{%endblock%}

{%block content%}

<h3>All Reviews</h3>
{%for review in page_obj%}
    <div class="container posts-content">
        <div class="row">
            <div class="col-lg-6">
                <div class="card mb-4">
                  <div class="card-body">
                    <div class="media mb-3">
                      <img src="{{review.user.profile_picture.url}}" class="d-block ui-w-40 rounded-circle" alt="">
                      <div class="media-body ml-3">
                        <b>{{review.user.username}}</b> rated "{{review.book.title}}" {{review.stars_given}} stars
                        <div class="text-muted small">{{review.created_at | date:"M d, Y"}}</div>
                      </div>
                    </div>

                    <p>
                      {{review.comment | truncatechars:300}}
                    </p>
                    <a href="javascript:void(0)" class="ui-rect ui-bg-cover" style="background-image: url('{{review.book.book_cover.url}}');"></a>
                  </div>
                </div>
            </div>
        </div>
    </div>
{%endfor%}
 <nav>
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page=1">&laquo; first</a></li>
                <li class="page-item"><a class="page-link" href="?page={{page_obj.previous_page_number}}">previous</a></li>
            {% endif %}

            <li class="page-item active">
                <a href="#" class="page-link">{{page_obj.number}}</a>
            </li>

            {% if page_obj.has_next%}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last&raquo;</a></li>
            {% endif %}
        </ul>
    </nav>
{%endblock%}

templates/landing.html
{% extends 'base.html' %}

{%block content%}

    <div id="box">
        <h1>Welcome to GoodReads-Clone</h1>
    </div>

    <hr class="border border-danger border-2 opacity-50">
    <div class="row">
        <div class="col-4">
            <ul class="list-group">
                <li class="list-group-item active"><h3>About us</h3></li>
                <li class="list-group-item"><b>Full Name</b>: Ismoiljon Abdumajidov</li>
                <li class="list-group-item"><b>Birth </b>: 17.06.2003 (Uzbekistan, Andijan region)</li>
                <li class="list-group-item"><b>Username</b>: Network_Warrior</li>
                <li class="list-group-item"><b>Residency</b>: Uzbekistan</li>
                <li class="list-group-item"><b>Occupation</b>: Student (Poland, University of Lodz.<br>Computer-Science faculty)</li>
                <li class="list-group-item"><b>Staff Status</b>: Owner</li>
            </ul>
        </div>
        <div class="col-7 ms-5">
            <ul class="list-group float-end">
                <li class="list-group-item active"><h3>Tools used </h3></li>
                <li class="list-group-item">HTL, CSS, JAVASCRIPT</li>
                <li class="list-group-item">PYTHON and DJANGO</li>
                <li class="list-group-item">PostgreSQL</li>
                <li class="list-group-item">DRF</li>
                <li class="list-group-item">UNIT TEST</li>
                <li class="list-group-item">CELERY</li>
                <li class="list-group-item">RabbitMQ</li>
                <li class="list-group-item">COMMANDLINE</li>
            </ul>
        </div>
    </div>

    {%if user_obj%}
    <hr class="border border-danger border-2 opacity-50">
    <h3>Community Members</h3>
    <div class="row">
        {%for user in user_obj%}
            <div class=" mt-5 col-3">
                <p>{{user.username}}</p>
                <img class="profile-pic" src="{{user.profile_picture.url}}">
            </div>
        {%endfor%}
    </div>
    <nav>
        <ul class="pagination mt-3">
            {% if user_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page=1">&laquo; first</a></li>
                <li class="page-item"><a class="page-link" href="?page={{user_obj.previous_page_number}}">previous</a></li>
            {% endif %}

            <li class="page-item active">
                <a href="#" class="page-link">{{user_obj.number}}</a>
            </li>

            {% if user_obj.has_next%}
                <li class="page-item"><a class="page-link" href="?page={{ user_obj.next_page_number }}">next</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ user_obj.paginator.num_pages }}">last&raquo;</a></li>
            {% endif %}
        </ul>
    </nav>
{%endif%}


{%endblock content%}

templates/not_found.html
<h2>Not Found</h2>
<p>The requested resource was not found on this server!! here some links that can be helpful :</p>
<ul>
  <li>
    <a href="{%url 'landing'%}">HOME</a>
  </li>
</ul>