api/urls.py
from django.urls import path
from .views import DetailReviewAPIView, ReviewListAPIView

app_name='api'
urlpatterns = [
    path('reviews/', ReviewListAPIView.as_view(), name="review_list"),
    path('reviews/<int:id>/', DetailReviewAPIView.as_view(), name="review_detail")
]

books/urls.py
from django.urls import path
from .views import BooksView, BooksDetailView, BooksReviewsView, EditReviewView, DeleteReviewView, \
    DeleteCompleteReview, BooksAuthorView

app_name='books'
urlpatterns = [
    path('', BooksView.as_view(), name='list'),
    path('<int:id>/', BooksDetailView.as_view(), name='detail'),
    path('<int:book_id>/author/<int:author_id>', BooksAuthorView.as_view(), name='author'),
    path('<int:id>/reviews/', BooksReviewsView.as_view(), name='reviews'),
    path('<int:book_id>/reviews/<int:review_id>/edit/', EditReviewView.as_view(), name='edit_review'),
    path('<int:book_id>/reviews/<int:review_id>/delete/', DeleteReviewView.as_view(), name='delete_review'),
    path('<int:book_id>/reviews/<int:review_id>/delete/complete/', DeleteCompleteReview.as_view(), name='delete_complete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import landing_page, home_page
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', landing_page, name='landing'),
    path('home/', home_page, name='home_page'),
    path('account/', include('account.urls')),
    path('books/', include('books.urls')),
    path('api/', include("api.urls")),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'config.views.handle_not_found'



books/models.py
from account.models import CustomUser as User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models


# Create your models here.
from django.utils import timezone


class Book(models.Model):
    title = models.CharField(max_length=150)
    description = models.TextField()
    isbn = models.CharField(max_length=17)
    book_cover = models.ImageField(default='cover_book.png')

    def __str__(self):
        return self.title


class Author(models.Model):
    first_name = models.CharField(max_length=120)
    last_name = models.CharField(max_length=120)
    email = models.EmailField(blank=True)
    bio = models.TextField()
    born = models.CharField(max_length=120)
    residency = models.CharField(max_length=150, blank=True)
    motto = models.TextField(blank=True)
    author_image = models.ImageField(default='default_author.png')

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def full_name(self):
        return f"{self.first_name} {self.last_name}"


class BookAuthor(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)


    def __str__(self):
        return f'{self.book.title} by {self.author.first_name}'


class BookReview(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    comment = models.TextField()
    stars_given = models.FloatField(
        validators=[MinValueValidator(1), MaxValueValidator(5)]
    )
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.stars_given} stars by {self.user.username} for '{self.book.title}'"


books/forms.py
from django import forms
from .models import BookReview


class BookReviewsForm(forms.ModelForm):
    stars_given = forms.FloatField(min_value=1, max_value=5)

    class Meta:
        model = BookReview
        fields = ('stars_given', 'comment')

books/views.py
from books.models import BookReview, Book, Author
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View
from .forms import BookReviewsForm
from django.views.generic import ListView, DetailView



# Create your views here.

# class BooksView(ListView):
#   template_name = 'books/list.html'
#  queryset = Book.objects.all()
#  context_object_name = 'books'
#  paginate_by = 2


class BooksView(View):
    def get(self, request):
        books = Book.objects.all().order_by('id')
        search_query = request.GET.get('q', '')
        if search_query:
            books = books.filter(title__icontains=search_query)
        page_size = request.GET.get('page_size', 2)
        paginator = Paginator(books, page_size)
        page_num = request.GET.get('page', 1)
        page_obj = paginator.get_page(page_num)
        return render(
            request,
            'books/list.html',
            {'page_obj': page_obj, 'search': search_query}
        )


class BooksDetailView(View):
    def get(self, request, id):
        book = Book.objects.get(id=id)
        review_form = BookReviewsForm()
        return render(request, 'books/detail.html', {'book': book, 'form': review_form})


class BooksAuthorView(View):
    def get(self, request, book_id, author_id):
        book = Book.objects.get(id=book_id)
        author = Author.objects.get(id=author_id)
        book_author = author.bookauthor_set.all().order_by('id')
        page_size = request.GET.get('page_size', 8)
        paginator = Paginator(book_author, page_size)
        page_num = request.GET.get('page', 1)
        page_ob = paginator.get_page(page_num)
        return render(request, 'books/author.html', {'book':book, 'author':author, 'page_obj':page_ob})


class BooksReviewsView(LoginRequiredMixin, View):
    def post(self, request, id):
        book = Book.objects.get(id=id)
        review_form = BookReviewsForm(data=request.POST)
        if review_form.is_valid():
            BookReview.objects.create(
                user = request.user,
                book = book,
                stars_given = review_form.cleaned_data['stars_given'],
                comment = review_form.cleaned_data['comment']
            )
            return redirect(reverse('books:detail', kwargs={'id':book.id}))
        return render(request, 'books/detail.html', {'book': book, 'form': review_form, 'num':4})


class EditReviewView(LoginRequiredMixin, View):
    def get(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.bookreview_set.get(id=review_id)
        review_form = BookReviewsForm(instance=review)
        return render(request, 'books/edit_review.html', {'book':book, 'review':review, 'form':review_form})

    def post(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.bookreview_set.get(id=review_id)
        review_form = BookReviewsForm(instance=review, data=request.POST)
        if review_form.is_valid():
            review_form.save()
            return redirect(reverse('books:detail', kwargs={'id':book.id}))

        return render(request, 'books/edit_review.html', {'book':book, 'review':review, 'form':review_form})


class DeleteReviewView(LoginRequiredMixin, View):
    def get(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.bookreview_set.get(id=review_id)
        return render(request, 'books/delete_review.html', {'book':book, 'review':review})


class DeleteCompleteReview(LoginRequiredMixin, View):
    def get(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.bookreview_set.get(id=review_id)
        review.delete()
        messages.success(request, f"Review has been successfully deleted")
        return redirect(reverse('books:detail', kwargs={'id':book.id}))

books/templates/books/author.html
{%extends 'base.html'%}
{%block title%}author page{%endblock%}
{%block content%}
<h1>{{author.full_name}}</h1>

<div class="row me-2">
    <div class="col-2 mt-2">
        <img class="cover-pic" src="{{author.author_image.url}}">
    </div>
    <div class="col-9 mt-3 ms-5">
        <p>{{author.bio}}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <div class="mt-3">
            <p><b>Born</b>: {{author.born}}</p>
            {%if author.residency%}
                <p><b>Residency</b>: {{author.residency}}</p>
            {%endif%}
            {%if author.email%}
                <p><b>Email</b>: {{author.email}}</p>
            {%endif%}
        </div>
    </div>
</div>


{%if page_obj%}
    <hr class="border border-danger border-2 opacity-50">
    <h5>All books written by {{author.last_name}}</h5>
    <div class="row">
        {%for book_author in page_obj%}
            <div class=" mt-5 col-3">
                <p><a href="{%url 'books:detail' book_author.book.id%}">{{book_author.book.title}}</a></p>
                <img class="cover-pic" src="{{book_author.book.book_cover.url}}">
            </div>
        {%endfor%}
    </div>
    <nav>
        <ul class="pagination mt-3">
            {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page=1">&laquo; first</a></li>
                <li class="page-item"><a class="page-link" href="?page={{page_obj.previous_page_number}}">previous</a></li>
            {% endif %}

            <li class="page-item active">
                <a href="#" class="page-link">{{page_obj.number}}</a>
            </li>

            {% if page_obj.has_next%}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last&raquo;</a></li>
            {% endif %}
        </ul>
    </nav>
{%endif%}

<div class="card">
  <div class="card-body ">
    <blockquote class="blockquote mb-0">
      <footer class="blockquote-footer mt-2"> {{author.motto}} <cite title="Source Title">"{{author.full_name}}"</cite></footer>
    </blockquote>
  </div>
</div>
<br>
{%endblock%}

books/templates/books/delete_review.html
{%extends 'base.html'%}
{%block title%}Delete{%endblock%}
{%block content%}
<h3>Are you sure want to delete this review ?</h3>
<p>
    <b>Book</b>: {{book.title}}
</p>
<p>
    <b>Review</b>: {{review.comment}}
</p>
<a href="{%url 'books:delete_complete' book.id review.id%}" class="btn btn-outline-danger">Yes</a> <a class="btn btn-outline-primary" href="{{request.META.HTTP_REFERER}}">No</a>
{%endblock content%}

books/templates/books/detail.html
{%extends 'base.html'%}
{% load crispy_forms_tags %}
{%block title%}Detail{%endblock%}
{%block content%}

    <div class="row mb-3">
        <div class="col-2">
            <img class="cover-pic" alt="Not found." src="{{book.book_cover.url}}">
        </div>

        <div class="col-6 ms-3">
            <h3>{{book.title}}</h3>
            <span class="fst-italic">
                Authored by
                {%for book_author in book.bookauthor_set.all%}
                    {%if forloop.end%}
                        <a href="{%url 'books:author' book.id book_author.author.id%}">{{book_author.author.full_name}}</a>
                    {%else%}
                        <a href="{%url 'books:author' book.id book_author.author.id%}">{{book_author.author.full_name}},</a>
                    {%endif%}
                {%endfor%}
            </span>
            <p>{{book.description}}</p>
        </div>
    </div>
    <div class="row mb-4">
        <div class="col-6">
            <form method="post" action="{% url 'books:reviews' book.id%}">
                {%csrf_token%}
                {{form | crispy}}
                <br>
                <button class="btn btn-success">Add review</button>
            </form>
        </div>
    </div>
    {% if book.bookreview_set.exists %}
        <h4> Reviews </h4>
        <hr>
        {% for review in book.bookreview_set.all%}
            <div class="row mb-3">
                <div class="col-1 me-2">
                    <img class="small-profile-pic" src="{{review.user.profile_picture.url}}">
                </div>
                <div class="col-7">
                    <b>{{review.user.username}}</b> rated {{review.stars_given}} stars <span class="fw-lighter">{{review.created_at}}</span>
                    {%if review.user == request.user%}
                        <a href="{%url 'books:edit_review' book.id review.id%}"><i class="bi bi-pen"></i></a>
                        <a href="{%url  'books:delete_review' book.id review.id%}"><i class="bi bi-trash"></i></a>
                    {%endif%}
                    <p class="mt-2 font-monospace">{{review.comment}}</p>
                </div>
            </div>
        {% endfor %}
    {%endif%}
{%endblock content%}

books/templates/books/edit_review.html
{%extends 'base.html'%}
{%load crispy_forms_tags%}
{%block title%}Edit Reviews{%endblock%}
{%block content%}

<div class="row mb-4">
        <div class="col-6">
            <form method="post" action="{% url 'books:edit_review' book.id review.id%}">
                {%csrf_token%}
                {{form | crispy}}
                <button class="btn btn-success">Save</button>
            </form>
        </div>
    </div>
{%endblock content%}

books/templates/books/list.html
{%extends 'base.html'%}
{%block title%}Books Page{%endblock%}

{%block content%}
<h3>Books</h3>

<div class="row mb-3">
    <div class="col-4">
        <form method="get" class="d-flex">
            <input class="form-control" type="text" placeholder="Search" name="q" value="{{search}}">
            <button class=" ms-2 btn btn-success">Search</button>
        </form>
    </div>
</div>

{% if page_obj %}
    {% for book in page_obj.object_list %}
        <div class="row mb-4">
            <div class="col-2">
                    <img class="cover-pic" src="{{book.book_cover.url}}">
            </div>
            <div class="col-6 ms-4">
                    <a href="{% url 'books:detail' book.id %}">{{book.title}}</a>
                    <p>
                        {{book.description}}
                    </p>
            </div>
        </div>

    {% endfor %}
    <nav>
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page=1">&laquo; first</a></li>
                <li class="page-item"><a class="page-link" href="?page={{page_obj.previous_page_number}}">previous</a></li>
            {% endif %}

            <li class="page-item active">
                <a href="#" class="page-link">{{page_obj.number}}</a>
            </li>

            {% if page_obj.has_next%}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last&raquo;</a></li>
            {% endif %}
        </ul>
    </nav>

{% else %}
    No books found.
{% endif %}
{%endblock content%}


